### ISSUE TITLE
未能找到作者改进的地方

### ISSUE THREAD

**Issue by lovelyyoshino** [cumtchenchang/VINS-Fusion-mobile-robot#1]
您好作者，目前我正在研究如何在VINS-FUSION上改进算法，找到您的项目，但是没有找到您在readme里面提到的方案

**Comment by edgar-explorer** [comment]
HI&nbsp;因为工作之后有保密协议&nbsp;我的代码已经很长时间没有更新了
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年7月21日(星期三)&nbsp;中午1:44
***@***.***&gt;;
***@***.***&gt;;
主题:[cumtchenchang/VINS-Fusion-mobile-robot]&nbsp;未能找到作者改进的地方&nbsp;(#1)



 
您好作者，目前我正在研究如何在VINS-FUSION上改进算法，找到您的项目，但是没有找到您在readme里面提到的方案
 
&mdash;

**Comment by lovelyyoshino** [comment]
收到，谢谢你的回复，我已经找到更好的解决方法

**Comment by bulingda** [comment]
> 收到，谢谢你的回复，我已经找到更好的解决方法

请问你都改进了哪些地方呢？可以分享一下吗？
